#ifndef DEF_CONSTANTES
#define DEF_CONSTANTES

    #define TAILLE_BLOC         25
    #define NB_BLOCS_LARGEUR    12
    #define NB_BLOCS_HAUTEUR    21
    #define LIMITE_ZONE_GAUCHE  60
    #define LIMITE_ZONE_DROITE  LIMITE_ZONE_GAUCHE+TAILLE_BLOC * (NB_BLOCS_LARGEUR-2)
    #define LIMITE_ZONE_HAUT    50
    #define LIMITE_ZONE_BAS     LIMITE_ZONE_HAUT+TAILLE_BLOC * (NB_BLOCS_HAUTEUR-1)
    #define LARGEUR_FENETRE     TAILLE_BLOC * NB_BLOCS_LARGEUR+200
    #define HAUTEUR_FENETRE     TAILLE_BLOC * NB_BLOCS_HAUTEUR+100
    #define ZONE_SCORE_Y    	LIMITE_ZONE_HAUT+100
    #define ZONE_SCORE_X    	LIMITE_ZONE_DROITE+160

    enum {BAS, GAUCHE, DROITE,AUTRE};
    enum {VIDE, CARRE_MOUVANT, CARRE_FIXE,LIMITE};
    enum {CARRE_O, CARRE_A, CARRE_B, CARRE_C, CARRE_D,CARRE_E,CARRE_F,CARRE_G};

#endif
